### PR TITLE
Handle newest format of archive name for latest mongodb versions on osx

### PR DESCRIPTION
**Pull request by mathieug**

### CODE REVIEW

**Comment by nodkz** [comment]
Thanks for PR!
Please add test cases for 3.6 and 3.4 versions:
https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/__tests__/MongoBinaryDownloadUrl-test.js#L47

**Comment by mathieug** [comment]
Okay I've changed my mind, I'm adding an option "ssl" instead of checking the version. I'm going to push in a few.

**Comment by nodkz** [comment]
Don't forget to add additional option to https://github.com/nodkz/mongodb-memory-server#available-options

Thanks.

**Comment by mathieug** [comment]
Here you go @nodkz. I've also removed the useless binary option http.

**Comment by mathieug** [comment]
I have some troubles with typescript, I need to specify that ssl is optional and default to false.

**Comment by nodkz** [comment]
Thanks a lot! Good work 👌

**Pull request merged**
