### PR TITLE
Fix high-sev https-proxy-agent vuln

### LINKED ISSUE #238: npm audit vuln still present in `mongodb-memory-server-core`
#235 is separate

### PR DESCRIPTION
**Pull request by cktang88**
Fixes #238

### CODE REVIEW

**Comment by cktang88** [comment]
@nodkz can you take a look at this?

**Comment by nodkz** [comment]
Already implemented in https://github.com/nodkz/mongodb-memory-server/pull/236

Please try the latest 5.2.9

And close this PR if the problem resolved in 5.2.9

Thanks.

**Comment by tioback** [comment]
I just (15 minutes ago) downloaded mongodb-memory-server-global@5.2.9 and the problem is still there.

**Comment by nodkz** [comment]
@cktang88 thanks for reporting!

I'm closing your Pull Request cause fixed it in much more stronger way:
- Reassembling dependencies in monorepos' packages https://github.com/nodkz/mongodb-memory-server/commit/5b8459ca73bd43e2357da386728a6e736fd6d5de
- Your changes applied here https://github.com/nodkz/mongodb-memory-server/commit/c554faa3de6aee10be33cd5abbcb64eaa53cd8c3

Please check the fresh 5.2.11 version
Thanks!

**Comment by nodkz** [comment]
I spent the whole day in debugging MongoClient topology for ReplicaSet problem with error: "Maximum call stack size exceeded":

https://github.com/nodkz/mongodb-memory-server/commit/470f09485d5caa9062fc1c24fb5efc0eb3d7d32f

Without this my test fails.

**Pull request closed without merging**
