### PR TITLE
Fix URL generation for MongoDB 4.4

### PR DESCRIPTION
**Pull request by tinovyatkin**
This PR fixes download URL generation for MongoDB 4.4 for macOS and Windows platforms.

### CODE REVIEW

**Comment by nodkz** [comment]
@tinovyatkin thanks a lot for code improvements and this fix! 👍

**Comment by SebastienElet** [comment]
@nodkz can we have a release for this one please ? 🙏

**Comment by nodkz** [comment]
@SebastienElet thanks for your message.
Codecov failed on CI 15 days ago. I've just restarted a job and a new version should be published from minute to minute.

**Comment by tinovyatkin** [comment]
@nodkz FYI, you may switch off codecov commit status for `master` merging via `.codecov.yml`:

```yaml
coverage:
  status:
    project:
      default:
        only_pulls: true
    patch:
      default:
        only_pulls: true
```

**Pull request merged**
