### PR TITLE
wait for mongod process to exit before removing its files

### PR DESCRIPTION
**Pull request by gvuyk**
#26

### CODE REVIEW

**Comment by nodkz** [comment]
@gvuyk Thanks for PR! It forces to me on the small refactoring of `MongoInstance`.

Add `kill()` and `getPid()` methods. Also method `run()` now returns `MongoInstance` not `childProcess`. It allows to call `MongoInstance.kill()` method in tests in one line with ensure that process was killed.

Please check that tests pass in your env.
I made changes in your branch `bug-issue#26`. Just pull it from your forked repo.
Thanks.

**Comment by gvuyk** [comment]
Nice!
At MongoInstance-test.js, is there a particular reason for killing mongod on next tick?

**Comment by nodkz** [comment]
Hm, really no reason for next tick.

**Comment by nodkz** [comment]
Thanks for contribution. 👍

New version with your changes already on npm.

**Pull request merged**
