### PR TITLE
Transpile mongo_killer.js script

### PR DESCRIPTION
**Pull request by AJRdev**
Resolves issue :  https://github.com/nodkz/mongodb-memory-server/issues/151

### CODE REVIEW

**Comment by AJRdev** [comment]
CI is failling because locally when the tests are run (so before transpilation) the mongo_killer.js file is not available, a quick fix to this is to have at the same time in the repo a mongo_killer.js file and a mongo_killer.ts file.

**Comment by AJRdev** [comment]
Doing something like this https://github.com/TypeStrong/ts-node/issues/619 might be better but out of that I don't really see how can pass our local tests without the mongo_killer.js file available before transpilation..

**Comment by AhmedFat7y** [comment]
@AJRdev moving my comment to here

For the tests to pass with minimal intervention, could we mock `childprocess.spawn` to check for filename if it ends with `.ts` to add `ts-node`? Or mock the `MongoInstance._launchKiller` function to do so?

**Comment by nodkz** [comment]
@AJRdev I completely refactor your code ;)
Move `mongo_killer.js` and `postinstall.js` files to `scripts` folder.
And add `scripts` folder to the package.

It much better and simpler solution!

**Comment by AJRdev** [comment]
@nodkz Yes I was just thinking about doing that :p Perfect thanks ! I think we can merge this PR

**Pull request merged**
