### PR TITLE
feat(install): configure installation from package.json

### PR DESCRIPTION
**Pull request by kjarmicki**
Hi :)

I'd like to be able to install desired version of Mongo binary without having to prefix `npm install` with `MONGOMS_VERSION` and other env variables, and without slowing down my first run of tests. I think ability to declare binary installation options in package.json could be useful in this case.

### CODE REVIEW

**Comment by kjarmicki** [comment]
Wow, some things have seriously changed in this project structure since yesterday :open_mouth: 
Nevertheless, let me know if that PR makes sense to you and I'll try to adjust it to new project structure.

**Comment by nodkz** [comment]
Configure from package.json is the desired feature  (https://github.com/nodkz/mongodb-memory-server/issues/159#issuecomment-474706911). So, of course, your PR make sense.  👍

For now I see just one downside, that your config option is called `mongoDbMemoryServer`, existed ENV variables called `MONGOMS_*` and current lib has name `mongodb-memory-server` (in memory it by default, but can be used other storage engines).

So before introducing your feature may be better to rename this package. And give it to something universal?!

Do you have any ideas about how the package(s) can be named?

Restrictions:
- short name
- one-word
- same naming for packages, envs vars and config in package.json

**Comment by kjarmicki** [comment]
I think the current name is great actually :slightly_smiling_face: it made me find this package quick and it does exactly what the name says. I don't think one-word name would carry enough meaning to achieve the same effect.
You could try something like `mongo-launcher`, but again, I think current name is not the problem.

I agree that naming consistency is importnant, so maybe `MONGOMS_*` vars could be replaced by `MONGODB_MEMORY_SERVER_*`? Other names seem to be consistent.

On the side note, why did you introduce Lerna? It seems that subpackages are based on the Mongo version, which is just a configuration option, and most of the code is duplicated?

**Comment by nodkz** [comment]
Lerna allows publishing several packages from one repo. Several packages need to provide specific behavior and split lib into more granular parts (e.g., move replica set to another package, cause it requires `mongodb` package for reading RS state and now in `optionalDependencies`. And download `mongodb` driver package for 95% of users who do not use it is quite strange.). 

In other words, splitting into packages will allow building more great tooling around MongoDB.

**Comment by kjarmicki** [comment]
Agree about replicaSet :+1: I just thought about `mongodb-memory-server-global-3.4`, `...-3.6` and `...-4.0` as being a bit redundant, since they only seem to use one different configuration option and share most of the code.

**Comment by nodkz** [comment]
Yep, code reused. Differs only in config options. But such packages remarkably simplify library setup with zero configs.

And when you list packages, you understand what happens without digging configs. It just helpers not more.

Anyway, the core package must have the ability to be configured via package.json.configs.XXX.options.

Needs day or two for choosing a new package name.

**Comment by kjarmicki** [comment]
@nodkz should I backport my PR to the new project structure or do you feel like I should wait a bit more because there are other structural changes coming?

**Comment by nodkz** [comment]
Backport! And it will be shipped.

Upcoming changes only hit config key name. And it will not be a problem, cause all names will be charged to new one.

**Comment by nodkz** [comment]
Backport! And it will be shipped.

Upcoming changes only hit config key name. And it will not be a problem, cause all names will be charged to new one.

**Comment by kjarmicki** [comment]
Hey, sorry for the delay, sometimes life happens. I haven't forget about this PR :)

**Pull request closed without merging**
