### PR TITLE
using latest version

### PR DESCRIPTION
**Pull request by kthakar1990**
https-proxy-agent has received high sev. vulnerability. Using latest version we can overcome that.

### CODE REVIEW

**Comment by laruiss** [comment]
Fixes #235

**Comment by cktang88** [comment]
can we merge this?

**Comment by nodkz** [comment]
Thanks a lot!

**Comment by kthakar1990** [comment]
@nodkz can you reopen this PR or someone can quickly update minor thing? 
Need to add one more change. We need to bump the version for "https-proxy-agent" in "mongodb-memory-server-core" as well.

**Comment by nodkz** [comment]
Fixed in 5.2.11, also was fixed "maximum call stack size exceeded" for ReplicaSets.

**Pull request merged**
