### PR TITLE
Fixups from #358

### LINKED ISSUE #325: Define Commit Format
it would be better if there was an standard definition on how to structure commits

something like [Angular's](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format)

### LINKED ISSUE #356: Increase minimal NodeJS version to 10
Increase minimal needed engine (NodeJS) version to `10` because dependencies (like `camelcase`) have this requirement on newer versions, and it is the lowest `LTS/Maintenance` version of NodeJS

### PR DESCRIPTION
**Pull request by hasezoey**
- stub packages: replace `%Home` with `~`
- core package: update engine field to `10.15`
- readme: reflect changes
- add file `.github/CONTRIBUTING.md` with an modified copy of Angulars Commit Message Style Guide (for easy reference)
- add husky & commitlint
- run commitlint on `commit-msg`
- run tests on `pre-push` (because the tests in this package take long, just run them once before the push)

## Related Issues

- fixups for #358
- closes #325 
- closes #356

### CODE REVIEW

**Comment by hasezoey** [comment]
the only thing left to add, is as mentioned in #325 husky to enforce everything

**Comment by hasezoey** [comment]
added husky & commitlint, but somehow husky dosnt execute the tests on `pre-push`

**Comment by nodkz** [comment]
I wrote again a new letter to npm about whitelisting 4.2. 4.4 packages names. Let's wait a day or two before merging this PR.

**Comment by nodkz** [comment]
NPM allowed 4.2. 4.4 packages. Let's see how semantic-release will work now.

**Comment by nodkz** [comment]
Reconfigure a little bit husky https://github.com/nodkz/mongodb-memory-server/commit/e658cc4467c25cb54adf3c534a70fa45d1e9e331

Run tests on commit is a bad thing for the current repo. Tests run about 2 mins, so it's bad to hang users' commits for this period of time 🥶

**Comment by hasezoey** [comment]
> Run tests on commit is a bad thing for the current repo. Tests run about 2 mins, so it's bad to hang users' commits for this period of time cold_face

yes, thats why i tried to add it on `pre-push`, but this hooks just wouldnt trigger for me

**Pull request merged**
