### PR TITLE
Adds proxy support

### PR DESCRIPTION
**Pull request by ChrisSG**

### CODE REVIEW

**Comment by nodkz** [comment]
@ChrisSG  Thanks for PR.
Small changes for further developers and I ready to merge it.

Also, please take a look at broken tests https://travis-ci.org/nodkz/mongodb-memory-server/jobs/399085564
They can be called locally via `npm run test` command.

I'm very like the idea of getting proxy settings from yarn/npm! Brilliant idea!

**Comment by ChrisSG** [comment]
Updated the tests.

**Comment by nodkz** [comment]
@ChrisSG thanks a lot a new cool feature! I am happy to be working with you!!!

**Comment by ChrisSG** [comment]
Thank you for the great module!

**Pull request merged**
