### PR TITLE
Upgrade build and publish procedures 

### PR DESCRIPTION
**Pull request by nodkz**
- Add new packages `mongodb-memory-server-global-4.2`, `mongodb-memory-server-global-4.4`
- Migrate from `circle ci` to `github actions`. If we started using them so better to unify CI system.
- Migrate from `lerna publish` back on `semantic-release`. I found a solution in its configs on how to support monorepos with multiple packages. I cannot live without semantic-release comments in PR & issues.

### CODE REVIEW

**Comment by nodkz** [comment]
@hasezoey please review this PR. Better to do it by every commit basis. 

For now, I'm merging this PR for checking the `publish` procedure to ensure that everything works well with semantic-release. So if you will have any notes, please, let me know in this or new one issue. Thanks.

**Comment by nodkz** [comment]
@hasezoey everything works well except publishing new packages `4.2`, `4.4`:
> 403 Forbidden - PUT https://registry.npmjs.org/mongodb-memory-server-global-4.2 - Package name triggered spam detection; if you believe this is in error, please contact support@npmjs.com

I wrote an email to them and awaiting their approval. I already did this several years ago.

PS. And one more thing: needs to check – that version changes in packages/**/packages.json will be applied at the next publish. It was a small [typo](https://github.com/nodkz/mongodb-memory-server/commit/ababe76482057566f6552ea983273c5dc8c0ff8f), but I happy that almost everything works from the first run.

PSS. Versions in published sub-packages were applied correctly – https://unpkg.com/browse/mongodb-memory-server@6.7.0/package.json, https://unpkg.com/browse/mongodb-memory-server-global-4.0@6.7.0/package.json

**Comment by hasezoey** [comment]
now it would be good to add the `engine` option to package.json (at least in core), and maybe to deprecate the packages <4.2 (4.0 dosnt exist on most modern distros)

and maybe some guide to know when an release happens

**Comment by hasezoey** [comment]
and another thing i noticed is that more than once per build the coverage is send to codecov (last commit it was node 10 & 14)

**Comment by nodkz** [comment]
> now it would be good to add the engine option to package.json (at least in core), and maybe to deprecate the packages <4.2 (4.0 dosnt exist on most modern distros)

What engine do you want to add? >=10 Honestly, I don't like this option. It will block installing our packages via npm. BUT it may work on lower nodejs versions with warnings. So I think better to see warnings than play with npm install options which neglect engine check. Or I something missing and engine helps to solve some issues?

Package 3.6 we should keep, it is still quite popular. With 4.0 I agree, let's deprecate it after publishing 4.2 & 4.4 to npm. It took a day or two in the past when they had added me to whitelists for publishing.

**Comment by hasezoey** [comment]
> So I think better to see warnings than play with npm install options which neglect engine check. Or I something missing and engine helps to solve some issues?

#356 #351

**Comment by nodkz** [comment]
@hasezoey if you have a Stripe account please consider the addition of Sponsor button to this repo. You spend quite a lot of time supporting this repo. And I hope the community will support you somehow.

I cannot do it myself because Stripe doesn't available in my country.

**Comment by hasezoey** [comment]
>  if you have a Stripe account please consider the addition of Sponsor button to this repo

i dont have one

**Comment by hasezoey** [comment]
just noticed (with 6.7.0 and 6.7.1) that no more release notes are added here in github, is this supposed to not happen?

**Comment by nodkz** [comment]
It's due to errors with publishing 4.2 & 4.4 packages.
Npm blocks them. I'm waiting for their response.

ср, 9 сент. 2020 г. в 19:28, hasezoey <notifications@github.com>:

**Comment by hasezoey** [comment]
didnt know this affect the release-tags, because the changelog gets generated normally

**Comment by hasezoey** [comment]
please look at the [current build log for `publish`](https://github.com/nodkz/mongodb-memory-server/runs/1095234768) it failed to push the CHANGELOG, because of branch protection ...

**Comment by nodkz** [comment]
[`master` branch protections](https://github.com/nodkz/mongodb-memory-server/issues/362#issuecomment-689531653) reverted to default state. 

Now github actions work without errors https://github.com/nodkz/mongodb-memory-server/runs/1095638937?check_suite_focus=true

**Pull request merged**
